"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const authMiddleware_1 = require("../middlewares/authMiddleware");
const auth_controller_1 = require("../controller/auth/auth-controller");
const re_send_otp_1 = require("../controller/auth/re-send-otp");
const verify_otp_1 = require("../controller/auth/verify-otp");
const forgot_password_1 = require("../controller/auth/forgot-password");
const router = (0, express_1.Router)();
router.post("/auth/register", authMiddleware_1.secureApi, auth_controller_1.registerUser);
router.post("/auth/login", authMiddleware_1.secureApi, auth_controller_1.login);
router.post("/auth/resend-otp", authMiddleware_1.secureApi, re_send_otp_1.resendOTP);
router.post("/auth/verify-otp", authMiddleware_1.secureApi, verify_otp_1.verifyOTP);
router.post("/auth/forgot-password", authMiddleware_1.secureApi, forgot_password_1.resetPassword);
exports.default = router;
